# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5df2ff2cfacb692405efc0fa9e1ba6057f675b0182c0a869065fea0438c06d5770c04c0764de8d4b00d1db3e9fa1231d442a39f03636da72eb935f98a3a65f23

test:
  secret_key_base: b8ffa9d6654faa6052a8173b58f531efc30aaf0ad5db0d3a793bd5b9d45fd56297b5442da59d87486aa182d195fb94e6cb14c4349d308f9975dd48292e89f1c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
